# compose.yml
version: '3.1'
services:
  db:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_USER: musicuser
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: music
    volumes:
       - ./postgresql/data:/var/lib/postgresql/data